// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PitchAiSkillPrincipal } from "./PitchAiSkillPrincipal";

export type SkillsListParams = {
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean,
/**
 * Authoritative tenant/user identity for a managed PitchAI skill profile.
 */
pitchaiPrincipal?: PitchAiSkillPrincipal | null, };
