// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoalSetParams = { threadId: string,
/**
 * Durable control-plane work identity whose callback completes with this goal.
 */
completionWorkId?: string | null,
/**
 * Opaque metadata published by the completion webhook producer.
 */
completionCallbackMetadata?: JsonValue | null, objective?: string | null, status?: ThreadGoalStatus | null, tokenBudget?: number | null, };
