// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadResidencyRecord = { threadId: string, loadedForSecs: bigint, idleForSecs: bigint, estimatedBytes?: bigint | null, resumeSource?: string | null, resumeDurationMs?: bigint | null, };
