// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadCallbackInsertParams = { deliveryId: string, eventId: string, completionWorkId: string, threadId: string, sourceAgentDisplayId: string, executionKind: string, executionId: string, terminalStatus: string, callbackText: string, finalText: string, terminalAtMs: bigint, payloadDigest: string, };
