// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadResidencyRecord } from "./ThreadResidencyRecord";

export type ThreadResidencyDiagnostics = { softCapBytes: bigint, hardCapBytes: bigint, idleMinTtlSecs: bigint, evictionPollSecs: bigint, rssBytes?: bigint | null, loadedThreads: number, residentEstimatedBytes: bigint, records: Array<ThreadResidencyRecord>, };
