// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadCallbackInsertOutcome } from "./ThreadCallbackInsertOutcome";
import type { ThreadCallbackInsertState } from "./ThreadCallbackInsertState";

export type ThreadCallbackInsertResponse = { outcome: ThreadCallbackInsertOutcome, state: ThreadCallbackInsertState, callId: string, needsRehydrate: boolean, };
