// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnInterruptParams = { threadId: string, turnId: string,
/**
 * When true, respond as soon as the interrupt request is accepted.
 * The client must still wait for `turn/completed` to observe final cleanup.
 */
respondImmediately?: boolean, };
