// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { UserInput } from "./UserInput";

export type TurnSteerParams = {threadId: string, clientUserMessageId?: string | null, /**
 * Durable control-plane work identity whose callback completes with the active turn.
 */
completionWorkId?: string | null, /**
 * Opaque metadata published by the completion webhook producer.
 */
completionCallbackMetadata?: JsonValue | null, input: Array<UserInput>, /**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string};
