// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";
import type { TurnStartSubmissionStatus } from "./TurnStartSubmissionStatus";

export type TurnStartResponse = { turn: Turn, submissionStatus: TurnStartSubmissionStatus,
/**
 * The active turn that this accepted submission was queued behind.
 *
 * Present only when `submissionStatus` is `queued` and the app-server
 * could identify the active turn at submission time.
 */
queuedBehindTurnId?: string, };
