// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnInterruptResponseStatus } from "./TurnInterruptResponseStatus";

export type TurnInterruptResponse = { threadId: string, turnId: string, status: TurnInterruptResponseStatus, };
