// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletionGateStartedEvent = { thread_id: string, turn_id: string, criteria_hash: string, judge_model: string, };
