// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompletionGateBlockedStopEvent = { thread_id: string, turn_id: string, criteria_hash: string, judge_model: string, request_id?: string, latency_ms: bigint, reason: string, continue_prompt: string, };
